# Generated by Django 4.2.7 on 2023-11-27 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("AccountID", models.AutoField(primary_key=True, serialize=False)),
                ("AccountName", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("CustomerID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=255)),
                ("Contact", models.CharField(max_length=255)),
                ("Location", models.CharField(max_length=255)),
                ("Notes", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("EmployeeID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=255)),
                ("Salary", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="ExpenseTransaction",
            fields=[
                ("ExpenseID", models.AutoField(primary_key=True, serialize=False)),
                ("TransactionDate", models.DateField()),
                ("Amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Description", models.TextField()),
                (
                    "AccountID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="luckybunapp.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("ItemID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=255)),
                ("Description", models.TextField()),
                (
                    "Type",
                    models.CharField(
                        choices=[
                            ("Inventory", "Inventory"),
                            ("Tool", "Tool"),
                            ("Ingredient", "Ingredient"),
                        ],
                        default="ingredient",
                        max_length=20,
                    ),
                ),
                ("Quantity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                ("OrderID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "Status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Shipped", "Shipped"),
                            ("Processing", "Processing"),
                            ("Completed", "Completed"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "PaymentStatus",
                    models.CharField(
                        choices=[("Paid", "Paid"), ("Unpaid", "Unpaid")],
                        default="Unpaid",
                        max_length=20,
                    ),
                ),
                ("OrderDate", models.DateField()),
                (
                    "CustomerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="luckybunapp.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("ProductID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=255)),
                ("Description", models.TextField()),
                ("Price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("StockQuantity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Production",
            fields=[
                ("ProductionID", models.AutoField(primary_key=True, serialize=False)),
                ("QuantityProduced", models.IntegerField()),
                ("ProductionDate", models.DateField()),
                ("ExpirationDate", models.DateField()),
                (
                    "ProductID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="luckybunapp.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                ("ShipmentID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "ShipmentStatus",
                    models.CharField(
                        choices=[("Complete", "Complete"), ("Partial", "Partial")],
                        default="Partial",
                        max_length=20,
                    ),
                ),
                (
                    "OrderID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="luckybunapp.orders",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StyleVariants",
            fields=[
                ("StyleId", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=255)),
                ("variant", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ShipmentItems",
            fields=[
                (
                    "ShipmentItemsID",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("QuantityShipped", models.IntegerField()),
                ("ShipmentDate", models.DateField()),
                (
                    "ProductID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="luckybunapp.product",
                    ),
                ),
                (
                    "ProductionID",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="luckybunapp.production",
                    ),
                ),
                (
                    "ShipmentID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="luckybunapp.shipment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesTransaction",
            fields=[
                ("SaleID", models.AutoField(primary_key=True, serialize=False)),
                ("TransactionDate", models.DateField()),
                ("Amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "AccountID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="luckybunapp.account",
                    ),
                ),
                (
                    "OrderID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="luckybunapp.orders",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalaryTransaction",
            fields=[
                ("SalaryID", models.AutoField(primary_key=True, serialize=False)),
                ("TransactionDate", models.DateField()),
                ("Amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "AccountID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="luckybunapp.account",
                    ),
                ),
                (
                    "EmployeeID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="luckybunapp.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefundTransaction",
            fields=[
                (
                    "RefundTransactionID",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("TransactionDate", models.DateField()),
                ("RefundAmount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "AccountID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="luckybunapp.account",
                    ),
                ),
                (
                    "CustomerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="luckybunapp.customer",
                    ),
                ),
                (
                    "OrderID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="luckybunapp.orders",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductReturn",
            fields=[
                ("ReturnID", models.AutoField(primary_key=True, serialize=False)),
                ("ReturnDate", models.DateField()),
                ("ReturnReason", models.CharField(max_length=255)),
                ("QuantityReturned", models.IntegerField()),
                (
                    "CustomerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="luckybunapp.customer",
                    ),
                ),
                (
                    "OrderID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="luckybunapp.orders",
                    ),
                ),
                (
                    "ProductID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="luckybunapp.product",
                    ),
                ),
                (
                    "ProductionID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="luckybunapp.production",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductItems",
            fields=[
                ("ProductID", models.AutoField(primary_key=True, serialize=False)),
                ("RequiredQuantity", models.IntegerField()),
                (
                    "ItemID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="luckybunapp.item",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("subtitle", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=250, unique=True)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Draft", "Draft"), ("Published", "Published")],
                        default="Draft",
                        max_length=10,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_author",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="OrderItems",
            fields=[
                (
                    "OrderItemId",
                    models.AutoField(default=1, primary_key=True, serialize=False),
                ),
                ("Quantity", models.IntegerField()),
                (
                    "OrderID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="luckybunapp.orders",
                    ),
                ),
                (
                    "ProductID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="luckybunapp.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemPurchase",
            fields=[
                ("PurchaseID", models.AutoField(primary_key=True, serialize=False)),
                ("Quantity", models.IntegerField()),
                ("PurchaseDate", models.DateField()),
                ("ExpirationDate", models.DateField()),
                ("AmountPaid", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "ExpenseID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="luckybunapp.expensetransaction",
                    ),
                ),
                (
                    "ItemID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="luckybunapp.item",
                    ),
                ),
            ],
        ),
    ]
