# Generated by Django 4.2.7 on 2023-11-10 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('AccountID', models.IntegerField(primary_key=True, serialize=False)),
                ('AccountName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Contact', models.CharField(max_length=255)),
                ('Location', models.CharField(max_length=255)),
                ('Notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseTransaction',
            fields=[
                ('ExpenseID', models.IntegerField(primary_key=True, serialize=False)),
                ('TransactionDate', models.DateField()),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Description', models.TextField()),
                ('AccountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luckybunapp.account')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('ItemID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Type', models.CharField(choices=[('Ingredient', 'Ingredient'), ('Tool', 'Tool'), ('Inventory', 'Inventory')], max_length=20)),
                ('Quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Completed', 'Completed')], max_length=20)),
                ('OrderID', models.IntegerField(primary_key=True, serialize=False)),
                ('OrderDate', models.DateField()),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luckybunapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('StockQuantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('ProductionID', models.IntegerField(primary_key=True, serialize=False)),
                ('QuantityProduced', models.IntegerField()),
                ('ProductionDate', models.DateField()),
                ('ExpirationDate', models.DateField()),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luckybunapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('ShipmentStatus', models.CharField(choices=[('Partial', 'Partial'), ('Complete', 'Complete')], max_length=20)),
                ('ShipmentID', models.IntegerField(primary_key=True, serialize=False)),
                ('ShipmentDate', models.DateField()),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luckybunapp.orders')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentItems',
            fields=[
                ('QuantityShipped', models.IntegerField(primary_key=True, serialize=False)),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luckybunapp.product')),
                ('ShipmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luckybunapp.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='SalesTransaction',
            fields=[
                ('SaleID', models.IntegerField(primary_key=True, serialize=False)),
                ('TransactionDate', models.DateField()),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('AccountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luckybunapp.account')),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luckybunapp.orders')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryTransaction',
            fields=[
                ('SalaryID', models.IntegerField(primary_key=True, serialize=False)),
                ('TransactionDate', models.DateField()),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('AccountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luckybunapp.account')),
                ('EmployeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luckybunapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='RefundTransaction',
            fields=[
                ('RefundTransactionID', models.IntegerField(primary_key=True, serialize=False)),
                ('TransactionDate', models.DateField()),
                ('RefundAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('AccountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luckybunapp.account')),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luckybunapp.customer')),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luckybunapp.orders')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReturn',
            fields=[
                ('ReturnID', models.IntegerField(primary_key=True, serialize=False)),
                ('ReturnDate', models.DateField()),
                ('ReturnReason', models.CharField(max_length=255)),
                ('QuantityReturned', models.IntegerField()),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luckybunapp.customer')),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luckybunapp.orders')),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luckybunapp.product')),
                ('ProductionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luckybunapp.production')),
            ],
        ),
        migrations.CreateModel(
            name='ProductItems',
            fields=[
                ('RequiredQuantity', models.IntegerField(primary_key=True, serialize=False)),
                ('ItemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luckybunapp.item')),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luckybunapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('Quantity', models.IntegerField(primary_key=True, serialize=False)),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luckybunapp.orders')),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luckybunapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPurchase',
            fields=[
                ('PurchaseID', models.IntegerField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField()),
                ('PurchaseDate', models.DateField()),
                ('ExpirationDate', models.DateField()),
                ('AmountPaid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ExpenseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luckybunapp.expensetransaction')),
                ('ItemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luckybunapp.item')),
            ],
        ),
    ]
