# Generated by Django 4.2.7 on 2023-11-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("luckybunapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="Type",
            field=models.CharField(
                choices=[
                    ("Tool", "Tool"),
                    ("Inventory", "Inventory"),
                    ("Ingredient", "Ingredient"),
                ],
                default="ingredient",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderitems",
            name="OrderItemId",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="orders",
            name="PaymentStatus",
            field=models.CharField(
                choices=[("Unpaid", "Unpaid"), ("Paid", "Paid")],
                default="Unpaid",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="Status",
            field=models.CharField(
                choices=[
                    ("Processing", "Processing"),
                    ("Shipped", "Shipped"),
                    ("Completed", "Completed"),
                    ("Pending", "Pending"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("Published", "Published"), ("Draft", "Draft")],
                default="Draft",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="ShipmentStatus",
            field=models.CharField(
                choices=[("Partial", "Partial"), ("Complete", "Complete")],
                default="Partial",
                max_length=20,
            ),
        ),
    ]
