# Generated by Django 4.2.7 on 2023-11-30 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("luckybunapp", "0002_alter_item_type_alter_orderitems_orderitemid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expenses",
            fields=[
                ("ExpenseID", models.AutoField(primary_key=True, serialize=False)),
                ("Description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Purchases",
            fields=[
                ("PurchaseID", models.AutoField(primary_key=True, serialize=False)),
                ("Quantity", models.IntegerField()),
                (
                    "ExpenseID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="luckybunapp.expenses",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefundItems",
            fields=[
                ("RefundItemID", models.AutoField(primary_key=True, serialize=False)),
                ("Quantity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Refunds",
            fields=[
                ("RefundID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "CustomerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="luckybunapp.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Salaries",
            fields=[
                ("SalaryID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "EmployeeID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="luckybunapp.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sales",
            fields=[
                ("SaleID", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Transactions",
            fields=[
                ("TransactionID", models.AutoField(primary_key=True, serialize=False)),
                ("TransactionDate", models.DateField()),
                (
                    "TransactionType",
                    models.CharField(
                        choices=[("Debit", "Debit"), ("Credit", "Credit")],
                        default="Credit",
                        max_length=20,
                    ),
                ),
                ("Amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Description", models.TextField()),
                (
                    "AccountID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="luckybunapp.account",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="itempurchase",
            name="ExpenseID",
        ),
        migrations.RemoveField(
            model_name="itempurchase",
            name="ItemID",
        ),
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
        migrations.RemoveField(
            model_name="refundtransaction",
            name="AccountID",
        ),
        migrations.RemoveField(
            model_name="refundtransaction",
            name="CustomerID",
        ),
        migrations.RemoveField(
            model_name="refundtransaction",
            name="OrderID",
        ),
        migrations.RemoveField(
            model_name="salarytransaction",
            name="AccountID",
        ),
        migrations.RemoveField(
            model_name="salarytransaction",
            name="EmployeeID",
        ),
        migrations.RemoveField(
            model_name="salestransaction",
            name="AccountID",
        ),
        migrations.RemoveField(
            model_name="salestransaction",
            name="OrderID",
        ),
        migrations.RenameField(
            model_name="productitems",
            old_name="ItemID",
            new_name="InventoryItemID",
        ),
        migrations.AlterField(
            model_name="orders",
            name="PaymentStatus",
            field=models.CharField(
                choices=[("Paid", "Paid"), ("Unpaid", "Unpaid")],
                default="Unpaid",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="Status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Processing", "Processing"),
                    ("Shipped", "Shipped"),
                    ("Completed", "Completed"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.RenameModel(
            old_name="Item",
            new_name="InventoryItem",
        ),
        migrations.DeleteModel(
            name="ExpenseTransaction",
        ),
        migrations.DeleteModel(
            name="ItemPurchase",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.DeleteModel(
            name="RefundTransaction",
        ),
        migrations.DeleteModel(
            name="SalaryTransaction",
        ),
        migrations.DeleteModel(
            name="SalesTransaction",
        ),
        migrations.AddField(
            model_name="sales",
            name="OrderID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="luckybunapp.orders"
            ),
        ),
        migrations.AddField(
            model_name="sales",
            name="TransactionID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="luckybunapp.transactions",
            ),
        ),
        migrations.AddField(
            model_name="salaries",
            name="TransactionID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="luckybunapp.transactions",
            ),
        ),
        migrations.AddField(
            model_name="refunds",
            name="OrderID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="luckybunapp.orders"
            ),
        ),
        migrations.AddField(
            model_name="refunds",
            name="TransactionID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="luckybunapp.transactions",
            ),
        ),
        migrations.AddField(
            model_name="refunditems",
            name="OrderID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="luckybunapp.orders"
            ),
        ),
        migrations.AddField(
            model_name="refunditems",
            name="ProductID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="luckybunapp.product"
            ),
        ),
        migrations.AddField(
            model_name="purchases",
            name="InventoryItemID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="luckybunapp.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="expenses",
            name="TransactionID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="luckybunapp.transactions",
            ),
        ),
    ]
