# Generated by Django 4.2.7 on 2023-11-12 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("luckybunapp", "0002_alter_item_type_alter_orders_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="Type",
            field=models.CharField(
                choices=[
                    ("ingredient", "Ingredient"),
                    ("tool", "Tool"),
                    ("inventory", "Inventory"),
                ],
                default="ingredient",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="Status",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("shipped", "Shipped"),
                    ("processing", "Processing"),
                    ("pending", "Pending"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
