# Generated by Django 4.2.7 on 2023-11-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("luckybunapp", "0003_alter_item_type_alter_orders_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="PaymentStatus",
            field=models.CharField(
                choices=[("paid", "Paid"), ("unpaid", "Unpaid")],
                default="unpaid",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="Type",
            field=models.CharField(
                choices=[
                    ("tool", "Tool"),
                    ("inventory", "Inventory"),
                    ("ingredient", "Ingredient"),
                ],
                default="ingredient",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="Status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("completed", "Completed"),
                    ("pending", "Pending"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=10,
            ),
        ),
    ]
