# Generated by Django 4.2.7 on 2023-11-30 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "luckybunapp",
            "0003_expenses_purchases_refunditems_refunds_salaries_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItems",
            fields=[
                ("ItemID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=255)),
                ("Description", models.TextField()),
                (
                    "Type",
                    models.CharField(
                        choices=[
                            ("Ingredient", "Ingredient"),
                            ("Inventory", "Inventory"),
                            ("Tool", "Tool"),
                        ],
                        default="ingredient",
                        max_length=20,
                    ),
                ),
                ("Quantity", models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name="Account",
            new_name="Accounts",
        ),
        migrations.RenameModel(
            old_name="Customer",
            new_name="Customers",
        ),
        migrations.RenameModel(
            old_name="Employee",
            new_name="Employees",
        ),
        migrations.RenameModel(
            old_name="ProductReturn",
            new_name="ProductReturns",
        ),
        migrations.RenameModel(
            old_name="Product",
            new_name="Products",
        ),
        migrations.RenameModel(
            old_name="Shipment",
            new_name="Shipments",
        ),
        migrations.AlterField(
            model_name="orders",
            name="PaymentStatus",
            field=models.CharField(
                choices=[("Unpaid", "Unpaid"), ("Paid", "Paid")],
                default="Unpaid",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="Status",
            field=models.CharField(
                choices=[
                    ("Processing", "Processing"),
                    ("Shipped", "Shipped"),
                    ("Pending", "Pending"),
                    ("Completed", "Completed"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="TransactionType",
            field=models.CharField(
                choices=[("Credit", "Credit"), ("Debit", "Debit")],
                default="Credit",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="productitems",
            name="InventoryItemID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="luckybunapp.inventoryitems",
            ),
        ),
        migrations.AlterField(
            model_name="purchases",
            name="InventoryItemID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="luckybunapp.inventoryitems",
            ),
        ),
        migrations.DeleteModel(
            name="InventoryItem",
        ),
    ]
