# Generated by Django 4.2.7 on 2023-11-12 16:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("luckybunapp", "0005_alter_orders_paymentstatus_alter_orders_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipment",
            name="ShipmentDate",
        ),
        migrations.AddField(
            model_name="shipmentitems",
            name="ProductionID",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="luckybunapp.production",
            ),
        ),
        migrations.AddField(
            model_name="shipmentitems",
            name="ShipmentDate",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="expensetransaction",
            name="TransactionDate",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="Type",
            field=models.CharField(
                choices=[
                    ("inventory", "Inventory"),
                    ("tool", "Tool"),
                    ("ingredient", "Ingredient"),
                ],
                default="ingredient",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="itempurchase",
            name="ExpirationDate",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="itempurchase",
            name="PurchaseDate",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="orders",
            name="OrderDate",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="orders",
            name="Status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("shipped", "Shipped"),
                    ("completed", "Completed"),
                    ("processing", "Processing"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="production",
            name="ExpirationDate",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="production",
            name="ProductionDate",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="productreturn",
            name="ReturnDate",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="refundtransaction",
            name="TransactionDate",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="salarytransaction",
            name="TransactionDate",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="salestransaction",
            name="TransactionDate",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="ShipmentStatus",
            field=models.CharField(
                choices=[("complete", "Complete"), ("partial", "Partial")],
                default="partial",
                max_length=20,
            ),
        ),
    ]
