# Generated by Django 4.2.7 on 2023-11-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("luckybunapp", "0006_remove_shipment_shipmentdate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expensetransaction",
            name="TransactionDate",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="itempurchase",
            name="ExpirationDate",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="itempurchase",
            name="PurchaseDate",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="orders",
            name="OrderDate",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="orders",
            name="PaymentStatus",
            field=models.CharField(
                choices=[("paid", "Paid"), ("unpaid", "Unpaid")],
                default="unpaid",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="Status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="production",
            name="ExpirationDate",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="production",
            name="ProductionDate",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="productreturn",
            name="ReturnDate",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="refundtransaction",
            name="TransactionDate",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="salarytransaction",
            name="TransactionDate",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="salestransaction",
            name="TransactionDate",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="ShipmentStatus",
            field=models.CharField(
                choices=[("partial", "Partial"), ("complete", "Complete")],
                default="partial",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="shipmentitems",
            name="ShipmentDate",
            field=models.DateField(),
        ),
    ]
